// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Slider_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Blank
void ui_Blank_screen_init(void);
void ui_event_Blank(lv_event_t * e);
lv_obj_t * ui_Blank;
// CUSTOM VARIABLES

// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t * ui_Home;
lv_obj_t * ui_Header;
lv_obj_t * ui_Container2;
void ui_event_Manual(lv_event_t * e);
lv_obj_t * ui_Manual;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Container6;
void ui_event_Manual3(lv_event_t * e);
lv_obj_t * ui_Manual3;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Container8;
void ui_event_Manual4(lv_event_t * e);
lv_obj_t * ui_Manual4;
lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_ManualMode
void ui_ManualMode_screen_init(void);
lv_obj_t * ui_ManualMode;
lv_obj_t * ui_Header1;
lv_obj_t * ui_TabView2;
lv_obj_t * ui_Jog_Mode;
lv_obj_t * ui_Move;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Slider;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Sliderbox;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Footer;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Container13;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Image22;
lv_obj_t * ui_power;
lv_obj_t * ui_Image23;
lv_obj_t * ui_Position_Mode;
lv_obj_t * ui_Slider7;
lv_obj_t * ui_Image31;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Sliderbox5;
lv_obj_t * ui_Image24;
lv_obj_t * ui_Label34;
lv_obj_t * ui_Image25;
lv_obj_t * ui_Slider8;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label35;
lv_obj_t * ui_Button13;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Footer2;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Container5;
void ui_event_Button12(lv_event_t * e);
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Image11;
lv_obj_t * ui_power2;
lv_obj_t * ui_Image9;
// CUSTOM VARIABLES
lv_obj_t * uic_TabView2;

// SCREEN: ui_ABMode
void ui_ABMode_screen_init(void);
lv_obj_t * ui_ABMode;
lv_obj_t * ui_Header2;
lv_obj_t * ui_Move2;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Button5;
lv_obj_t * ui_Image14;
lv_obj_t * ui_Slider6;
lv_obj_t * ui_Image20;
lv_obj_t * ui_Informer;
lv_obj_t * ui_Sliderbox4;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Image18;
lv_obj_t * ui_Image21;
lv_obj_t * ui_Label19;
lv_obj_t * ui_Image19;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Footer3;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Container14;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Image27;
lv_obj_t * ui_power3;
lv_obj_t * ui_Image28;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Start;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Stop;
lv_obj_t * ui_Label27;
lv_obj_t * ui_Loop;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Save;
lv_obj_t * ui_Label28;
lv_obj_t * ui_TimeValue;
lv_obj_t * ui_Label30;
lv_obj_t * ui_SetA;
lv_obj_t * ui_Label25;
lv_obj_t * ui_SetAValue;
lv_obj_t * ui_Label29;
lv_obj_t * ui_SetAValue1;
lv_obj_t * ui_Label32;
lv_obj_t * ui_Time;
lv_obj_t * ui_Label26;
lv_obj_t * ui_SetB;
lv_obj_t * ui_Label31;
// CUSTOM VARIABLES

// SCREEN: ui_Calibration
void ui_Calibration_screen_init(void);
lv_obj_t * ui_Calibration;
lv_obj_t * ui_Header4;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Slider5;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Container12;
lv_obj_t * ui_Sliderbox3;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Footer4;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Container15;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Image29;
lv_obj_t * ui_power4;
lv_obj_t * ui_Image30;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label15;
// CUSTOM VARIABLES

// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
lv_obj_t * ui_Splash;
lv_obj_t * ui_Image1;
// CUSTOM VARIABLES
lv_obj_t * uic_Image1;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Blank(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Splash, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Splash_screen_init);
    }
}

void ui_event_Manual(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ManualMode, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ManualMode_screen_init);
    }
}

void ui_event_Manual3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ABMode, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ABMode_screen_init);
    }
}

void ui_event_Manual4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Calibration, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Calibration_screen_init);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Splash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_Home_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Blank_screen_init();
    ui_Home_screen_init();
    ui_ManualMode_screen_init();
    ui_ABMode_screen_init();
    ui_Calibration_screen_init();
    ui_Splash_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Blank);
}
