// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Slider_UI

#ifndef _SLIDER_UI_UI_H
#define _SLIDER_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Blank
void ui_Blank_screen_init(void);
void ui_event_Blank(lv_event_t * e);
extern lv_obj_t * ui_Blank;
// CUSTOM VARIABLES

// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Image1;

// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Header;
extern lv_obj_t * ui_Container2;
void ui_event_Manual(lv_event_t * e);
extern lv_obj_t * ui_Manual;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container6;
void ui_event_Manual3(lv_event_t * e);
extern lv_obj_t * ui_Manual3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container8;
void ui_event_Manual4(lv_event_t * e);
extern lv_obj_t * ui_Manual4;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_ManualMode
void ui_ManualMode_screen_init(void);
extern lv_obj_t * ui_ManualMode;
extern lv_obj_t * ui_Header1;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_Jog_Mode;
extern lv_obj_t * ui_Move;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_SpeedValue;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Container3;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Slider;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_SliderPosition;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Position_Mode;
extern lv_obj_t * ui_Slider7;
extern lv_obj_t * ui_Image31;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Sliderbox5;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Image25;
void ui_event_Slider8(lv_event_t * e);
extern lv_obj_t * ui_Slider8;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_PositionValue;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Footer2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Container5;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_power2;
extern lv_obj_t * ui_Image9;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TabView2;

// SCREEN: ui_ABMode
void ui_ABMode_screen_init(void);
extern lv_obj_t * ui_ABMode;
extern lv_obj_t * ui_Header2;
extern lv_obj_t * ui_Move2;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Slider6;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_SliderPosition3;
void ui_event_Slider9(lv_event_t * e);
extern lv_obj_t * ui_Slider9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_SliderPosition1;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_SliderPosition4;
extern lv_obj_t * ui_Footer3;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Container14;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_power3;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Start;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Stop;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Loop;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Save;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_TimeValue;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_SetA;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_SetAValue;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_SetAValue1;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_SetB;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_SetB1;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_SetB2;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES

// SCREEN: ui_Calibration
void ui_Calibration_screen_init(void);
void ui_event_Calibration(lv_event_t * e);
extern lv_obj_t * ui_Calibration;
extern lv_obj_t * ui_Header4;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Footer4;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Container15;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_power4;
extern lv_obj_t * ui_Image30;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Slider5;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_SliderPosition2;
void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_rk_logo_png);    // assets/RK_Logo.png
LV_IMG_DECLARE(ui_img_rk_logo_40_40_png);    // assets/RK_Logo_40_40.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_hand_16725997_png);    // assets/hand_16725997.png
LV_IMG_DECLARE(ui_img_adapt_10984466_png);    // assets/adapt_10984466.png
LV_IMG_DECLARE(ui_img_time_14147652_png);    // assets/time_14147652.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_back2_png);    // assets/back2.png
LV_IMG_DECLARE(ui_img_group_4_png);    // assets/Group 4.png
LV_IMG_DECLARE(ui_img_infomer_png);    // assets/Infomer.png
LV_IMG_DECLARE(ui_img_box_png);    // assets/box.png
LV_IMG_DECLARE(ui_img_16417679);    // assets/icon-park-solid_back.png
LV_IMG_DECLARE(ui_img_rectangle_163_png);    // assets/Rectangle 163.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
