// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Slider_UI

#include "ui.h"

void ui_ABMode_screen_init(void)
{
    ui_ABMode = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ABMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header2 = ui_Header_create(ui_ABMode);
    lv_obj_set_x(ui_Header2, 0);
    lv_obj_set_y(ui_Header2, -360);

    lv_label_set_text(ui_comp_get_child(ui_Header2, UI_COMP_HEADER_LABEL1), "AB Shuttle");

    ui_Move2 = lv_obj_create(ui_ABMode);
    lv_obj_remove_style_all(ui_Move2);
    lv_obj_set_width(ui_Move2, 480);
    lv_obj_set_height(ui_Move2, 150);
    lv_obj_set_x(ui_Move2, 1);
    lv_obj_set_y(ui_Move2, -15);
    lv_obj_set_align(ui_Move2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Move2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button11 = lv_button_create(ui_Move2);
    lv_obj_set_width(ui_Button11, 150);
    lv_obj_set_height(ui_Button11, 150);
    lv_obj_set_x(ui_Button11, -149);
    lv_obj_set_y(ui_Button11, 1);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_image_create(ui_Button11);
    lv_image_set_src(ui_Image17, &ui_img_back_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_Move2);
    lv_obj_set_width(ui_Panel6, 120);
    lv_obj_set_height(ui_Panel6, 150);
    lv_obj_set_x(ui_Panel6, -2);
    lv_obj_set_y(ui_Panel6, 1);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x31363B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -1);
    lv_obj_set_y(ui_Label17, -1);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "50 \nmm/s");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_Move2);
    lv_obj_set_width(ui_Button5, 150);
    lv_obj_set_height(ui_Button5, 150);
    lv_obj_set_x(ui_Button5, 151);
    lv_obj_set_y(ui_Button5, 0);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image14 = lv_image_create(ui_Button5);
    lv_image_set_src(ui_Image14, &ui_img_back2_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider6 = lv_obj_create(ui_ABMode);
    lv_obj_remove_style_all(ui_Slider6);
    lv_obj_set_width(ui_Slider6, 462);
    lv_obj_set_height(ui_Slider6, 157);
    lv_obj_set_x(ui_Slider6, -1);
    lv_obj_set_y(ui_Slider6, -180);
    lv_obj_set_align(ui_Slider6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Slider6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_Slider6);
    lv_image_set_src(ui_Image13, &ui_img_group_4_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 389
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image13, -5);
    lv_obj_set_y(ui_Image13, -37);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_Slider6);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 452);
    lv_obj_set_height(ui_Container9, 143);
    lv_obj_set_x(ui_Container9, -1);
    lv_obj_set_y(ui_Container9, 4);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_image_create(ui_Container9);
    lv_image_set_src(ui_Image15, &ui_img_infomer_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Image15, 2);
    lv_obj_set_y(ui_Image15, 18);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderPosition3 = lv_label_create(ui_Image15);
    lv_obj_set_width(ui_SliderPosition3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SliderPosition3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SliderPosition3, 0);
    lv_obj_set_y(ui_SliderPosition3, 9);
    lv_obj_set_align(ui_SliderPosition3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SliderPosition3, "0");
    lv_obj_set_style_text_color(ui_SliderPosition3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SliderPosition3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderPosition3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPosition3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider9 = lv_slider_create(ui_Container9);
    lv_slider_set_value(ui_Slider9, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider9) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider9, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider9, 378);
    lv_obj_set_height(ui_Slider9, 44);
    lv_obj_set_x(ui_Slider9, -4);
    lv_obj_set_y(ui_Slider9, -41);
    lv_obj_set_align(ui_Slider9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider9, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider9, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider9, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider9, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider9, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Slider9, &ui_img_box_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider9, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider9,
                                                                                              lv_obj_get_style_pad_right(ui_Slider9, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Image10 = lv_image_create(ui_Container9);
    lv_image_set_src(ui_Image10, &ui_img_infomer_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Image10, -161);
    lv_obj_set_y(ui_Image10, 20);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderPosition1 = lv_label_create(ui_Image10);
    lv_obj_set_width(ui_SliderPosition1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SliderPosition1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SliderPosition1, 0);
    lv_obj_set_y(ui_SliderPosition1, 9);
    lv_obj_set_align(ui_SliderPosition1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SliderPosition1, "A");
    lv_obj_set_style_text_color(ui_SliderPosition1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SliderPosition1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderPosition1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPosition1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image16 = lv_image_create(ui_Container9);
    lv_image_set_src(ui_Image16, &ui_img_infomer_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Image16, 157);
    lv_obj_set_y(ui_Image16, 18);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderPosition4 = lv_label_create(ui_Image16);
    lv_obj_set_width(ui_SliderPosition4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SliderPosition4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SliderPosition4, 0);
    lv_obj_set_y(ui_SliderPosition4, 9);
    lv_obj_set_align(ui_SliderPosition4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SliderPosition4, "B");
    lv_obj_set_style_text_color(ui_SliderPosition4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SliderPosition4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderPosition4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPosition4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Footer3 = lv_obj_create(ui_ABMode);
    lv_obj_remove_style_all(ui_Footer3);
    lv_obj_set_width(ui_Footer3, 500);
    lv_obj_set_height(ui_Footer3, 54);
    lv_obj_set_x(ui_Footer3, 2);
    lv_obj_set_y(ui_Footer3, 378);
    lv_obj_set_align(ui_Footer3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Footer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel11 = lv_obj_create(ui_Footer3);
    lv_obj_set_width(ui_Panel11, 500);
    lv_obj_set_height(ui_Panel11, 50);
    lv_obj_set_x(ui_Panel11, -3);
    lv_obj_set_y(ui_Panel11, 0);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x8693A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel11, lv_color_hex(0x31363B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel11, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Footer3);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 63);
    lv_obj_set_height(ui_Container14, 27);
    lv_obj_set_x(ui_Container14, -194);
    lv_obj_set_y(ui_Container14, 0);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container14, 202, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_button_create(ui_Footer3);
    lv_obj_set_width(ui_Button14, 92);
    lv_obj_set_height(ui_Button14, 35);
    lv_obj_set_x(ui_Button14, -184);
    lv_obj_set_y(ui_Button14, -1);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button14, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -15);
    lv_obj_set_y(ui_Label23, 0);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Back");

    ui_Image27 = lv_image_create(ui_Button14);
    lv_image_set_src(ui_Image27, &ui_img_16417679);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image27, 26);
    lv_obj_set_y(ui_Image27, 0);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_power3 = lv_obj_create(ui_Footer3);
    lv_obj_set_width(ui_power3, 39);
    lv_obj_set_height(ui_power3, 40);
    lv_obj_set_x(ui_power3, 196);
    lv_obj_set_y(ui_power3, -1);
    lv_obj_set_align(ui_power3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_power3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_power3, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_power3, lv_color_hex(0x21CC3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_power3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_power3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_power3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_power3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image28 = lv_image_create(ui_power3);
    lv_image_set_src(ui_Image28, &ui_img_rectangle_163_png);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image28, 1);
    lv_obj_set_y(ui_Image28, 0);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel9 = lv_obj_create(ui_ABMode);
    lv_obj_set_width(ui_Panel9, 490);
    lv_obj_set_height(ui_Panel9, 233);
    lv_obj_set_x(ui_Panel9, 2);
    lv_obj_set_y(ui_Panel9, 236);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xE9F6F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Start = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Start, 100);
    lv_obj_set_height(ui_Start, 50);
    lv_obj_set_x(ui_Start, -177);
    lv_obj_set_y(ui_Start, 77);
    lv_obj_set_align(ui_Start, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Start, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Start, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Start, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Start, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Start, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Start, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Start);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Start");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label21, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label21, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Stop = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Stop, 100);
    lv_obj_set_height(ui_Stop, 50);
    lv_obj_set_x(ui_Stop, -57);
    lv_obj_set_y(ui_Stop, 76);
    lv_obj_set_align(ui_Stop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Stop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Stop, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Stop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Stop, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Stop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Stop);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Stop");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label27, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label27, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Loop = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Loop, 100);
    lv_obj_set_height(ui_Loop, 50);
    lv_obj_set_x(ui_Loop, 63);
    lv_obj_set_y(ui_Loop, 77);
    lv_obj_set_align(ui_Loop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Loop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Loop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Loop, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Loop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Loop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Loop, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Loop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Loop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Loop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Loop);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Loop");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label22, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label22, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Save = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Save, 100);
    lv_obj_set_height(ui_Save, 50);
    lv_obj_set_x(ui_Save, 180);
    lv_obj_set_y(ui_Save, 76);
    lv_obj_set_align(ui_Save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Save, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Save, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Save, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Save, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Save, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Save, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Save);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Save");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label28, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label28, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeValue = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_TimeValue, 100);
    lv_obj_set_height(ui_TimeValue, 50);
    lv_obj_set_x(ui_TimeValue, -56);
    lv_obj_set_y(ui_TimeValue, 5);
    lv_obj_set_align(ui_TimeValue, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TimeValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TimeValue, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TimeValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TimeValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TimeValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_TimeValue);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "10 s");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label30, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetA = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_SetA, 100);
    lv_obj_set_height(ui_SetA, 50);
    lv_obj_set_x(ui_SetA, -183);
    lv_obj_set_y(ui_SetA, -62);
    lv_obj_set_align(ui_SetA, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetA, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetA, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SetA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SetA, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetA, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_SetA);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Set A");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label25, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label25, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetAValue = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_SetAValue, 100);
    lv_obj_set_height(ui_SetAValue, 50);
    lv_obj_set_x(ui_SetAValue, -56);
    lv_obj_set_y(ui_SetAValue, -66);
    lv_obj_set_align(ui_SetAValue, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SetAValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SetAValue, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SetAValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetAValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetAValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetAValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetAValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_SetAValue);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "1000 mm");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label29, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetAValue1 = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_SetAValue1, 100);
    lv_obj_set_height(ui_SetAValue1, 50);
    lv_obj_set_x(ui_SetAValue1, 184);
    lv_obj_set_y(ui_SetAValue1, -66);
    lv_obj_set_align(ui_SetAValue1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SetAValue1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SetAValue1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SetAValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetAValue1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetAValue1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetAValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetAValue1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_SetAValue1);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "1000 mm");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label32, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Time, 100);
    lv_obj_set_height(ui_Time, 50);
    lv_obj_set_x(ui_Time, -179);
    lv_obj_set_y(ui_Time, 6);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Time, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Time, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Time, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Time, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Time);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Time");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label26, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label26, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetB = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_SetB, 100);
    lv_obj_set_height(ui_SetB, 50);
    lv_obj_set_x(ui_SetB, 68);
    lv_obj_set_y(ui_SetB, -66);
    lv_obj_set_align(ui_SetB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetB, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SetB, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SetB, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetB, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_SetB);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Set B");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label31, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label31, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetB1 = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_SetB1, 100);
    lv_obj_set_height(ui_SetB1, 50);
    lv_obj_set_x(ui_SetB1, 69);
    lv_obj_set_y(ui_SetB1, 7);
    lv_obj_set_align(ui_SetB1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetB1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetB1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetB1, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SetB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SetB1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetB1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetB1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_SetB1);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Back A");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label9, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetB2 = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_SetB2, 100);
    lv_obj_set_height(ui_SetB2, 50);
    lv_obj_set_x(ui_SetB2, 182);
    lv_obj_set_y(ui_SetB2, 7);
    lv_obj_set_align(ui_SetB2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetB2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetB2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetB2, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SetB2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SetB2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetB2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetB2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_SetB2);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Back B");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label20, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label20, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Slider9, ui_event_Slider9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);

}
