// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Slider_UI

#ifndef _UI_COMP_HEADER_H
#define _UI_COMP_HEADER_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Header
#define UI_COMP_HEADER_HEADER 0
#define UI_COMP_HEADER_PANEL3 1
#define UI_COMP_HEADER_IMAGE2 2
#define UI_COMP_HEADER_LABEL1 3
#define UI_COMP_HEADER_IMAGE3 4
#define UI_COMP_HEADER_BATTERY 5
#define _UI_COMP_HEADER_NUM 6
lv_obj_t * ui_Header_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
