// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Slider_UI

#include "ui.h"

// COMPONENT Header

lv_obj_t * ui_Header_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Header;
    cui_Header = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_Header);
    lv_obj_set_width(cui_Header, 484);
    lv_obj_set_height(cui_Header, 80);
    lv_obj_set_x(cui_Header, 0);
    lv_obj_set_y(cui_Header, -357);
    lv_obj_set_align(cui_Header, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Panel3;
    cui_Panel3 = lv_obj_create(cui_Header);
    lv_obj_set_width(cui_Panel3, 500);
    lv_obj_set_height(cui_Panel3, 80);
    lv_obj_set_x(cui_Panel3, -3);
    lv_obj_set_y(cui_Panel3, -2);
    lv_obj_set_align(cui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image2;
    cui_Image2 = lv_img_create(cui_Header);
    lv_img_set_src(cui_Image2, &ui_img_rk_logo_40_40_png);
    lv_obj_set_width(cui_Image2, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(cui_Image2, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_x(cui_Image2, -193);
    lv_obj_set_y(cui_Image2, -2);
    lv_obj_set_align(cui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_Header);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label1, -13);
    lv_obj_set_y(cui_Label1, 0);
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label1, "Home");
    lv_obj_set_style_text_color(cui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Image3;
    cui_Image3 = lv_img_create(cui_Header);
    lv_img_set_src(cui_Image3, &ui_img_battery_png);
    lv_obj_set_width(cui_Image3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_Image3, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(cui_Image3, 181);
    lv_obj_set_y(cui_Image3, 0);
    lv_obj_set_align(cui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HEADER_NUM);
    children[UI_COMP_HEADER_HEADER] = cui_Header;
    children[UI_COMP_HEADER_PANEL3] = cui_Panel3;
    children[UI_COMP_HEADER_IMAGE2] = cui_Image2;
    children[UI_COMP_HEADER_LABEL1] = cui_Label1;
    children[UI_COMP_HEADER_IMAGE3] = cui_Image3;
    lv_obj_add_event_cb(cui_Header, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Header, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Header_create_hook(cui_Header);
    return cui_Header;
}

