// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Slider_UI

#include "ui.h"

void ui_ManualMode_screen_init(void)
{
    ui_ManualMode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ManualMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_recolor(ui_ManualMode, lv_color_hex(0x929292), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ManualMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_recolor(ui_ManualMode, lv_color_hex(0x717171), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ManualMode, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ManualMode, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ManualMode, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Header1 = ui_Header_create(ui_ManualMode);
    lv_obj_set_x(ui_Header1, 0);
    lv_obj_set_y(ui_Header1, -360);

    lv_label_set_text(ui_comp_get_child(ui_Header1, UI_COMP_HEADER_LABEL1), "Manual");

    ui_TabView2 = lv_tabview_create(ui_ManualMode, LV_DIR_TOP, 100);
    lv_obj_set_width(ui_TabView2, 480);
    lv_obj_set_height(ui_TabView2, 685);
    lv_obj_set_x(ui_TabView2, 0);
    lv_obj_set_y(ui_TabView2, 18);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView2), &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_TabView2), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0xB5B5B5),
                                    LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(lv_tabview_get_tab_btns(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_TabView2), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Jog_Mode = lv_tabview_add_tab(ui_TabView2, "Jog Mode");

    ui_Move = lv_obj_create(ui_Jog_Mode);
    lv_obj_remove_style_all(ui_Move);
    lv_obj_set_width(ui_Move, 470);
    lv_obj_set_height(ui_Move, 150);
    lv_obj_set_x(ui_Move, -1);
    lv_obj_set_y(ui_Move, 126);
    lv_obj_set_align(ui_Move, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Move, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Move);
    lv_obj_set_width(ui_Button2, 150);
    lv_obj_set_height(ui_Button2, 150);
    lv_obj_set_x(ui_Button2, -149);
    lv_obj_set_y(ui_Button2, 1);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Button2);
    lv_img_set_src(ui_Image4, &ui_img_back_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Move);
    lv_obj_set_width(ui_Panel1, 120);
    lv_obj_set_height(ui_Panel1, 150);
    lv_obj_set_x(ui_Panel1, -2);
    lv_obj_set_y(ui_Panel1, 1);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x31363B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -1);
    lv_obj_set_y(ui_Label5, -1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "50 \nmm/s");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Move);
    lv_obj_set_width(ui_Button3, 150);
    lv_obj_set_height(ui_Button3, 150);
    lv_obj_set_x(ui_Button3, 151);
    lv_obj_set_y(ui_Button3, 0);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Button3);
    lv_img_set_src(ui_Image5, &ui_img_back2_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Jog_Mode);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 458);
    lv_obj_set_height(ui_Container3, 80);
    lv_obj_set_x(ui_Container3, 3);
    lv_obj_set_y(ui_Container3, 7);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1 = lv_slider_create(ui_Container3);
    lv_slider_set_value(ui_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 300);
    lv_obj_set_height(ui_Slider1, 50);
    lv_obj_set_x(ui_Slider1, -67);
    lv_obj_set_y(ui_Slider1, 7);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x818181), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container3);
    lv_obj_set_width(ui_Panel2, 100);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, 163);
    lv_obj_set_y(ui_Panel2, 7);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Panel2, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -1);
    lv_obj_set_y(ui_Label6, -3);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Speed");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider = lv_obj_create(ui_Jog_Mode);
    lv_obj_remove_style_all(ui_Slider);
    lv_obj_set_width(ui_Slider, 462);
    lv_obj_set_height(ui_Slider, 157);
    lv_obj_set_x(ui_Slider, -2);
    lv_obj_set_y(ui_Slider, -132);
    lv_obj_set_align(ui_Slider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Slider);
    lv_img_set_src(ui_Image6, &ui_img_group_4_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 389
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image6, -5);
    lv_obj_set_y(ui_Image6, -37);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container10 = lv_obj_create(ui_Slider);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 386);
    lv_obj_set_height(ui_Container10, 143);
    lv_obj_set_x(ui_Container10, -1);
    lv_obj_set_y(ui_Container10, 4);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Sliderbox = lv_obj_create(ui_Container10);
    lv_obj_remove_style_all(ui_Sliderbox);
    lv_obj_set_width(ui_Sliderbox, 100);
    lv_obj_set_height(ui_Sliderbox, 142);
    lv_obj_set_align(ui_Sliderbox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Sliderbox, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Sliderbox);
    lv_img_set_src(ui_Image7, &ui_img_infomer_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Image7, -5);
    lv_obj_set_y(ui_Image7, 12);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Image7);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 9);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "50");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Sliderbox);
    lv_img_set_src(ui_Image8, &ui_img_box_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image8, -6);
    lv_obj_set_y(ui_Image8, -39);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Footer = lv_obj_create(ui_Jog_Mode);
    lv_obj_remove_style_all(ui_Footer);
    lv_obj_set_width(ui_Footer, 500);
    lv_obj_set_height(ui_Footer, 54);
    lv_obj_set_x(ui_Footer, 2);
    lv_obj_set_y(ui_Footer, 378);
    lv_obj_set_align(ui_Footer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Footer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel8 = lv_obj_create(ui_Footer);
    lv_obj_set_width(ui_Panel8, 500);
    lv_obj_set_height(ui_Panel8, 50);
    lv_obj_set_x(ui_Panel8, -3);
    lv_obj_set_y(ui_Panel8, 0);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x8693A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel8, lv_color_hex(0x31363B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel8, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Footer);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 63);
    lv_obj_set_height(ui_Container13, 27);
    lv_obj_set_x(ui_Container13, -194);
    lv_obj_set_y(ui_Container13, 0);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container13, 202, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_Footer);
    lv_obj_set_width(ui_Button10, 92);
    lv_obj_set_height(ui_Button10, 35);
    lv_obj_set_x(ui_Button10, -184);
    lv_obj_set_y(ui_Button10, -1);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button10, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -15);
    lv_obj_set_y(ui_Label20, 0);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Back");

    ui_Image22 = lv_img_create(ui_Button10);
    lv_img_set_src(ui_Image22, &ui_img_16417679);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image22, 26);
    lv_obj_set_y(ui_Image22, 0);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_power = lv_obj_create(ui_Footer);
    lv_obj_set_width(ui_power, 39);
    lv_obj_set_height(ui_power, 40);
    lv_obj_set_x(ui_power, 196);
    lv_obj_set_y(ui_power, -1);
    lv_obj_set_align(ui_power, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_power, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_power, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_power, lv_color_hex(0x21CC3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_power, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image23 = lv_img_create(ui_power);
    lv_img_set_src(ui_Image23, &ui_img_rectangle_163_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image23, 1);
    lv_obj_set_y(ui_Image23, 0);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Position_Mode = lv_tabview_add_tab(ui_TabView2, "Position Mode");

    ui_Slider7 = lv_obj_create(ui_Position_Mode);
    lv_obj_remove_style_all(ui_Slider7);
    lv_obj_set_width(ui_Slider7, 476);
    lv_obj_set_height(ui_Slider7, 157);
    lv_obj_set_x(ui_Slider7, 0);
    lv_obj_set_y(ui_Slider7, -144);
    lv_obj_set_align(ui_Slider7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slider7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image31 = lv_img_create(ui_Slider7);
    lv_img_set_src(ui_Image31, &ui_img_group_4_png);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 389
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image31, -5);
    lv_obj_set_y(ui_Image31, -37);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Slider7);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 386);
    lv_obj_set_height(ui_Container4, 143);
    lv_obj_set_x(ui_Container4, -1);
    lv_obj_set_y(ui_Container4, 4);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Sliderbox5 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_Sliderbox5);
    lv_obj_set_width(ui_Sliderbox5, 100);
    lv_obj_set_height(ui_Sliderbox5, 142);
    lv_obj_set_align(ui_Sliderbox5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Sliderbox5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image24 = lv_img_create(ui_Sliderbox5);
    lv_img_set_src(ui_Image24, &ui_img_infomer_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Image24, -5);
    lv_obj_set_y(ui_Image24, 12);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_Image24);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, 0);
    lv_obj_set_y(ui_Label34, 9);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "50");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label34, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image25 = lv_img_create(ui_Sliderbox5);
    lv_img_set_src(ui_Image25, &ui_img_box_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image25, -6);
    lv_obj_set_y(ui_Image25, -39);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider8 = lv_slider_create(ui_Position_Mode);
    lv_slider_set_value(ui_Slider8, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider8) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider8, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider8, 429);
    lv_obj_set_height(ui_Slider8, 50);
    lv_obj_set_x(ui_Slider8, -11);
    lv_obj_set_y(ui_Slider8, 48);
    lv_obj_set_align(ui_Slider8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slider8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slider8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slider8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider8, lv_color_hex(0x818181), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider8, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider8, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider8, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Position_Mode);
    lv_obj_set_width(ui_Panel7, 429);
    lv_obj_set_height(ui_Panel7, 71);
    lv_obj_set_x(ui_Panel7, -9);
    lv_obj_set_y(ui_Panel7, 165);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xD2D3D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, -111);
    lv_obj_set_y(ui_Label35, 1);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "50  mm");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label35, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_btn_create(ui_Panel7);
    lv_obj_set_width(ui_Button13, 100);
    lv_obj_set_height(ui_Button13, 50);
    lv_obj_set_x(ui_Button13, 125);
    lv_obj_set_y(ui_Button13, 1);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button13, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Set");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label8, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Footer2 = lv_obj_create(ui_ManualMode);
    lv_obj_remove_style_all(ui_Footer2);
    lv_obj_set_width(ui_Footer2, 500);
    lv_obj_set_height(ui_Footer2, 54);
    lv_obj_set_x(ui_Footer2, 2);
    lv_obj_set_y(ui_Footer2, 378);
    lv_obj_set_align(ui_Footer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Footer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Footer2);
    lv_obj_set_width(ui_Panel5, 500);
    lv_obj_set_height(ui_Panel5, 50);
    lv_obj_set_x(ui_Panel5, -3);
    lv_obj_set_y(ui_Panel5, 0);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x8693A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel5, lv_color_hex(0x31363B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Footer2);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 63);
    lv_obj_set_height(ui_Container5, 27);
    lv_obj_set_x(ui_Container5, -194);
    lv_obj_set_y(ui_Container5, 0);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container5, 202, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_Footer2);
    lv_obj_set_width(ui_Button12, 92);
    lv_obj_set_height(ui_Button12, 35);
    lv_obj_set_x(ui_Button12, -184);
    lv_obj_set_y(ui_Button12, -1);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button12, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -15);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Back");

    ui_Image11 = lv_img_create(ui_Button12);
    lv_img_set_src(ui_Image11, &ui_img_16417679);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image11, 26);
    lv_obj_set_y(ui_Image11, 0);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_power2 = lv_obj_create(ui_Footer2);
    lv_obj_set_width(ui_power2, 39);
    lv_obj_set_height(ui_power2, 40);
    lv_obj_set_x(ui_power2, 196);
    lv_obj_set_y(ui_power2, -1);
    lv_obj_set_align(ui_power2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_power2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_power2, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_power2, lv_color_hex(0x21CC3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_power2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_power2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_power2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_power2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_img_create(ui_power2);
    lv_img_set_src(ui_Image9, &ui_img_rectangle_163_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image9, 1);
    lv_obj_set_y(ui_Image9, 0);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    uic_TabView2 = ui_TabView2;

}
