// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Slider_UI

#ifndef _SLIDER_UI_UI_H
#define _SLIDER_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Blank.h"
#include "ui_Splash.h"
#include "ui_ManualMode.h"
#include "ui_Home.h"
#include "ui_ABMode.h"
#include "ui_Calibration.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_rk_logo_png);    // assets/RK_Logo.png
LV_IMG_DECLARE(ui_img_rk_logo_40_40_png);    // assets/RK_Logo_40_40.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_back2_png);    // assets/back2.png
LV_IMG_DECLARE(ui_img_1157729664);    // assets/ic_baseline-plus.png
LV_IMG_DECLARE(ui_img_1381505174);    // assets/ic_baseline-minus.png
LV_IMG_DECLARE(ui_img_rectangle_114_png);    // assets/Rectangle 114.png
LV_IMG_DECLARE(ui_img_infomer_png);    // assets/Infomer.png
LV_IMG_DECLARE(ui_img_box_png);    // assets/box.png
LV_IMG_DECLARE(ui_img_16417679);    // assets/icon-park-solid_back.png
LV_IMG_DECLARE(ui_img_hand_16725997_png);    // assets/hand_16725997.png
LV_IMG_DECLARE(ui_img_adapt_10984466_png);    // assets/adapt_10984466.png
LV_IMG_DECLARE(ui_img_time_14147652_png);    // assets/time_14147652.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
