// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Slider_UI

#ifndef UI_ABMODE_H
#define UI_ABMODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ABMode
extern void ui_ABMode_screen_init(void);
extern void ui_ABMode_screen_destroy(void);
extern lv_obj_t * ui_ABMode;
extern lv_obj_t * ui_Header2;
extern lv_obj_t * ui_Footer3;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Container14;
extern void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Image27;
extern lv_obj_t * ui_power3;
extern lv_obj_t * ui_Image28;
extern lv_obj_t * ui_ABSetting;
extern lv_obj_t * ui_ABPoint;
extern lv_obj_t * ui_Slider6;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_SliderPositionAB;
extern void ui_event_positionAB(lv_event_t * e);
extern lv_obj_t * ui_positionAB;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Start;
extern lv_obj_t * ui_Starttext;
extern lv_obj_t * ui_Stop;
extern lv_obj_t * ui_StopText;
extern lv_obj_t * ui_SetA;
extern lv_obj_t * ui_SetAtext;
extern lv_obj_t * ui_SetAValue;
extern lv_obj_t * ui_SetAValue1;
extern lv_obj_t * ui_SetBValue;
extern lv_obj_t * ui_SetBValue1;
extern lv_obj_t * ui_SetB;
extern lv_obj_t * ui_Btext;
extern lv_obj_t * ui_BackA;
extern lv_obj_t * ui_BackAtext;
extern lv_obj_t * ui_BackB;
extern lv_obj_t * ui_BackBtext;
extern lv_obj_t * ui_PathSetting;
extern lv_obj_t * ui_Loops;
extern lv_obj_t * ui_LoopValue;
extern lv_obj_t * ui_SpeedValue3;
extern lv_obj_t * ui_Plusloop;
extern lv_obj_t * ui_Minusloop;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_ABSpeed;
extern void ui_event_speedSetAB(lv_event_t * e);
extern lv_obj_t * ui_speedSetAB;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_SpeedValueAB;
extern void ui_event_PlusAB(lv_event_t * e);
extern lv_obj_t * ui_PlusAB;
extern void ui_event_MinusAB(lv_event_t * e);
extern lv_obj_t * ui_MinusAB;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_SpeedValueBA;
extern lv_obj_t * ui_PlusBA;
extern lv_obj_t * ui_MinusBA;
extern lv_obj_t * ui_Label5;
extern void ui_event_speedSetBA(lv_event_t * e);
extern lv_obj_t * ui_speedSetBA;
extern lv_obj_t * ui_SwitchCS;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Header2_battery;
extern lv_obj_t * uic_SliderPositionAB;
extern lv_obj_t * uic_positionAB;
extern lv_obj_t * uic_Start;
extern lv_obj_t * uic_Stop;
extern lv_obj_t * uic_SetA;
extern lv_obj_t * uic_SetAValue;
extern lv_obj_t * uic_SetAValue1;
extern lv_obj_t * uic_SetBValue;
extern lv_obj_t * uic_SetBValue1;
extern lv_obj_t * uic_SetB;
extern lv_obj_t * uic_BackA;
extern lv_obj_t * uic_BackB;
extern lv_obj_t * uic_LoopValue;
extern lv_obj_t * uic_Plusloop;
extern lv_obj_t * uic_Minusloop;
extern lv_obj_t * uic_speedSetAB;
extern lv_obj_t * uic_SpeedValueAB;
extern lv_obj_t * uic_PlusAB;
extern lv_obj_t * uic_MinusAB;
extern lv_obj_t * uic_SpeedValueBA;
extern lv_obj_t * uic_PlusBA;
extern lv_obj_t * uic_MinusBA;
extern lv_obj_t * uic_speedSetBA;
extern lv_obj_t * uic_SwitchCS;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

