// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Slider_UI

#include "ui.h"

lv_obj_t * uic_SwitchCS;
lv_obj_t * uic_speedSetBA;
lv_obj_t * uic_MinusBA;
lv_obj_t * uic_PlusBA;
lv_obj_t * uic_SpeedValueBA;
lv_obj_t * uic_MinusAB;
lv_obj_t * uic_PlusAB;
lv_obj_t * uic_SpeedValueAB;
lv_obj_t * uic_speedSetAB;
lv_obj_t * uic_Minusloop;
lv_obj_t * uic_Plusloop;
lv_obj_t * uic_LoopValue;
lv_obj_t * uic_BackB;
lv_obj_t * uic_BackA;
lv_obj_t * uic_SetB;
lv_obj_t * uic_SetBValue1;
lv_obj_t * uic_SetBValue;
lv_obj_t * uic_SetAValue1;
lv_obj_t * uic_SetAValue;
lv_obj_t * uic_SetA;
lv_obj_t * uic_Stop;
lv_obj_t * uic_Start;
lv_obj_t * uic_positionAB;
lv_obj_t * uic_SliderPositionAB;
lv_obj_t * uic_Header2_battery;
lv_obj_t * ui_ABMode = NULL;
lv_obj_t * ui_Header2 = NULL;
lv_obj_t * ui_Footer3 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Button14 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Image27 = NULL;
lv_obj_t * ui_power3 = NULL;
lv_obj_t * ui_Image28 = NULL;
lv_obj_t * ui_ABSetting = NULL;
lv_obj_t * ui_ABPoint = NULL;
lv_obj_t * ui_Slider6 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_SliderPositionAB = NULL;
lv_obj_t * ui_positionAB = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Start = NULL;
lv_obj_t * ui_Starttext = NULL;
lv_obj_t * ui_Stop = NULL;
lv_obj_t * ui_StopText = NULL;
lv_obj_t * ui_SetA = NULL;
lv_obj_t * ui_SetAtext = NULL;
lv_obj_t * ui_SetAValue = NULL;
lv_obj_t * ui_SetAValue1 = NULL;
lv_obj_t * ui_SetBValue = NULL;
lv_obj_t * ui_SetBValue1 = NULL;
lv_obj_t * ui_SetB = NULL;
lv_obj_t * ui_Btext = NULL;
lv_obj_t * ui_BackA = NULL;
lv_obj_t * ui_BackAtext = NULL;
lv_obj_t * ui_BackB = NULL;
lv_obj_t * ui_BackBtext = NULL;
lv_obj_t * ui_PathSetting = NULL;
lv_obj_t * ui_Loops = NULL;
lv_obj_t * ui_LoopValue = NULL;
lv_obj_t * ui_SpeedValue3 = NULL;
lv_obj_t * ui_Plusloop = NULL;
lv_obj_t * ui_Minusloop = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_ABSpeed = NULL;
lv_obj_t * ui_speedSetAB = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_SpeedValueAB = NULL;
lv_obj_t * ui_PlusAB = NULL;
lv_obj_t * ui_MinusAB = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_SpeedValueBA = NULL;
lv_obj_t * ui_PlusBA = NULL;
lv_obj_t * ui_MinusBA = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_speedSetBA = NULL;
lv_obj_t * ui_SwitchCS = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions
void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_positionAB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SliderPositionJM, target, "", "");
    }
}

void ui_event_speedSetAB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SpeedValueAB, target, "", " mm/s");
    }
}

void ui_event_PlusAB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_slider_increment(ui_speedSetAB, 1, LV_ANIM_ON);
    }
}

void ui_event_MinusAB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_slider_increment(ui_speedSetAB, -1, LV_ANIM_ON);
    }
}

void ui_event_speedSetBA(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SpeedValueBA, target, "", " mm/s");
    }
}

// build funtions

void ui_ABMode_screen_init(void)
{
    ui_ABMode = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ABMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header2 = ui_Header_create(ui_ABMode);
    lv_obj_set_x(ui_Header2, 0);
    lv_obj_set_y(ui_Header2, -360);

    lv_label_set_text(ui_comp_get_child(ui_Header2, UI_COMP_HEADER_LABEL1), "AB Shuttle");

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_Footer3 = lv_obj_create(ui_ABMode);
    lv_obj_remove_style_all(ui_Footer3);
    lv_obj_set_width(ui_Footer3, 500);
    lv_obj_set_height(ui_Footer3, 54);
    lv_obj_set_x(ui_Footer3, 6);
    lv_obj_set_y(ui_Footer3, 378);
    lv_obj_set_align(ui_Footer3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Footer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel11 = lv_obj_create(ui_Footer3);
    lv_obj_set_width(ui_Panel11, 500);
    lv_obj_set_height(ui_Panel11, 50);
    lv_obj_set_x(ui_Panel11, -3);
    lv_obj_set_y(ui_Panel11, 0);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x8693A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel11, lv_color_hex(0x31363B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel11, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Footer3);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 63);
    lv_obj_set_height(ui_Container14, 27);
    lv_obj_set_x(ui_Container14, -194);
    lv_obj_set_y(ui_Container14, 0);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container14, 202, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_button_create(ui_Footer3);
    lv_obj_set_width(ui_Button14, 92);
    lv_obj_set_height(ui_Button14, 35);
    lv_obj_set_x(ui_Button14, -184);
    lv_obj_set_y(ui_Button14, -1);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button14, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button14, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Button14);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -15);
    lv_obj_set_y(ui_Label23, 0);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Back");

    ui_Image27 = lv_image_create(ui_Button14);
    lv_image_set_src(ui_Image27, &ui_img_16417679);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image27, 26);
    lv_obj_set_y(ui_Image27, 0);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_power3 = lv_obj_create(ui_Footer3);
    lv_obj_set_width(ui_power3, 39);
    lv_obj_set_height(ui_power3, 40);
    lv_obj_set_x(ui_power3, 196);
    lv_obj_set_y(ui_power3, -1);
    lv_obj_set_align(ui_power3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_power3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_power3, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_power3, lv_color_hex(0x21CC3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_power3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_power3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_power3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_power3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image28 = lv_image_create(ui_power3);
    lv_image_set_src(ui_Image28, &ui_img_rectangle_163_png);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image28, 1);
    lv_obj_set_y(ui_Image28, 0);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ABSetting = lv_tabview_create(ui_ABMode);
    lv_tabview_set_tab_bar_size(ui_ABSetting, 75);
    lv_obj_set_width(ui_ABSetting, 475);
    lv_obj_set_height(ui_ABSetting, 681);
    lv_obj_set_x(ui_ABSetting, 1);
    lv_obj_set_y(ui_ABSetting, 11);
    lv_obj_set_align(ui_ABSetting, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ABSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_ABSetting), &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ABPoint = lv_tabview_add_tab(ui_ABSetting, "ABPoint");

    ui_Slider6 = lv_obj_create(ui_ABPoint);
    lv_obj_remove_style_all(ui_Slider6);
    lv_obj_set_width(ui_Slider6, 462);
    lv_obj_set_height(ui_Slider6, 157);
    lv_obj_set_x(ui_Slider6, -1);
    lv_obj_set_y(ui_Slider6, -180);
    lv_obj_set_align(ui_Slider6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Slider6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_Slider6);
    lv_image_set_src(ui_Image13, &ui_img_rectangle_114_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 389
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image13, -5);
    lv_obj_set_y(ui_Image13, -37);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_Slider6);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 452);
    lv_obj_set_height(ui_Container9, 143);
    lv_obj_set_x(ui_Container9, -1);
    lv_obj_set_y(ui_Container9, 4);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_image_create(ui_Container9);
    lv_image_set_src(ui_Image15, &ui_img_infomer_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Image15, 2);
    lv_obj_set_y(ui_Image15, 18);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderPositionAB = lv_label_create(ui_Image15);
    lv_obj_set_width(ui_SliderPositionAB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SliderPositionAB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SliderPositionAB, 0);
    lv_obj_set_y(ui_SliderPositionAB, 9);
    lv_obj_set_align(ui_SliderPositionAB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SliderPositionAB, "0");
    lv_obj_set_style_text_color(ui_SliderPositionAB, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SliderPositionAB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderPositionAB, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPositionAB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_positionAB = lv_slider_create(ui_Container9);
    lv_slider_set_value(ui_positionAB, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_positionAB) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_positionAB, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_positionAB, 378);
    lv_obj_set_height(ui_positionAB, 44);
    lv_obj_set_x(ui_positionAB, -4);
    lv_obj_set_y(ui_positionAB, -41);
    lv_obj_set_align(ui_positionAB, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_positionAB, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionAB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_positionAB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_positionAB, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_positionAB, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_positionAB, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionAB, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_positionAB, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionAB, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_positionAB, &ui_img_box_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_positionAB, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_positionAB,
                                                                                                 lv_obj_get_style_pad_right(ui_positionAB, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Panel9 = lv_obj_create(ui_ABPoint);
    lv_obj_set_width(ui_Panel9, 490);
    lv_obj_set_height(ui_Panel9, 462);
    lv_obj_set_x(ui_Panel9, -7);
    lv_obj_set_y(ui_Panel9, 131);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xE9F6F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Start = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Start, 114);
    lv_obj_set_height(ui_Start, 67);
    lv_obj_set_x(ui_Start, -107);
    lv_obj_set_y(ui_Start, 97);
    lv_obj_set_align(ui_Start, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Start, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Start, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Start, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Start, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Start, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Start, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Starttext = lv_label_create(ui_Start);
    lv_obj_set_width(ui_Starttext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Starttext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Starttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Starttext, "Start");
    lv_obj_set_style_text_color(ui_Starttext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Starttext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Starttext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Starttext, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Starttext, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Stop = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_Stop, 132);
    lv_obj_set_height(ui_Stop, 67);
    lv_obj_set_x(ui_Stop, 99);
    lv_obj_set_y(ui_Stop, 94);
    lv_obj_set_align(ui_Stop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Stop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Stop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Stop, lv_color_hex(0xAD1862), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Stop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Stop, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Stop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Stop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Stop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopText = lv_label_create(ui_Stop);
    lv_obj_set_width(ui_StopText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StopText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopText, "Stop");
    lv_obj_set_style_text_color(ui_StopText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_StopText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_StopText, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StopText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetA = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_SetA, 126);
    lv_obj_set_height(ui_SetA, 74);
    lv_obj_set_x(ui_SetA, -144);
    lv_obj_set_y(ui_SetA, -158);
    lv_obj_set_align(ui_SetA, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetA, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetA, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SetA, lv_color_hex(0xC0980F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SetA, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetA, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetAtext = lv_label_create(ui_SetA);
    lv_obj_set_width(ui_SetAtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetAtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetAtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetAtext, "Set A");
    lv_obj_set_style_text_color(ui_SetAtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetAtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SetAtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_SetAtext, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetAtext, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetAValue = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_SetAValue, 116);
    lv_obj_set_height(ui_SetAValue, 82);
    lv_obj_set_x(ui_SetAValue, 19);
    lv_obj_set_y(ui_SetAValue, -156);
    lv_obj_set_align(ui_SetAValue, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SetAValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SetAValue, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SetAValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetAValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetAValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetAValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetAValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetAValue1 = lv_label_create(ui_SetAValue);
    lv_obj_set_width(ui_SetAValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetAValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetAValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetAValue1, "1000 mm");
    lv_obj_set_style_text_color(ui_SetAValue1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetAValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SetAValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetAValue1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetBValue = lv_obj_create(ui_Panel9);
    lv_obj_set_width(ui_SetBValue, 118);
    lv_obj_set_height(ui_SetBValue, 82);
    lv_obj_set_x(ui_SetBValue, 21);
    lv_obj_set_y(ui_SetBValue, -49);
    lv_obj_set_align(ui_SetBValue, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SetBValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SetBValue, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SetBValue, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetBValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetBValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetBValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetBValue, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetBValue1 = lv_label_create(ui_SetBValue);
    lv_obj_set_width(ui_SetBValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetBValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetBValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetBValue1, "1000 mm");
    lv_obj_set_style_text_color(ui_SetBValue1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetBValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SetBValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetBValue1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetB = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_SetB, 116);
    lv_obj_set_height(ui_SetB, 78);
    lv_obj_set_x(ui_SetB, -142);
    lv_obj_set_y(ui_SetB, -50);
    lv_obj_set_align(ui_SetB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SetB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetB, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SetB, lv_color_hex(0xC0980F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SetB, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetB, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Btext = lv_label_create(ui_SetB);
    lv_obj_set_width(ui_Btext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Btext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Btext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Btext, "Set B");
    lv_obj_set_style_text_color(ui_Btext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Btext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Btext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Btext, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Btext, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackA = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_BackA, 115);
    lv_obj_set_height(ui_BackA, 82);
    lv_obj_set_x(ui_BackA, 168);
    lv_obj_set_y(ui_BackA, -157);
    lv_obj_set_align(ui_BackA, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackA, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackA, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BackA, lv_color_hex(0xC0980F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BackA, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackA, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackAtext = lv_label_create(ui_BackA);
    lv_obj_set_width(ui_BackAtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackAtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackAtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackAtext, "Back A");
    lv_obj_set_style_text_color(ui_BackAtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackAtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BackAtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_BackAtext, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackAtext, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackB = lv_button_create(ui_Panel9);
    lv_obj_set_width(ui_BackB, 108);
    lv_obj_set_height(ui_BackB, 77);
    lv_obj_set_x(ui_BackB, 169);
    lv_obj_set_y(ui_BackB, -51);
    lv_obj_set_align(ui_BackB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackB, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BackB, lv_color_hex(0xC0980F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BackB, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackB, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackBtext = lv_label_create(ui_BackB);
    lv_obj_set_width(ui_BackBtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackBtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackBtext, 0);
    lv_obj_set_y(ui_BackBtext, -1);
    lv_obj_set_align(ui_BackBtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackBtext, "Back B");
    lv_obj_set_style_text_color(ui_BackBtext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackBtext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BackBtext, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_BackBtext, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackBtext, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PathSetting = lv_tabview_add_tab(ui_ABSetting, "PathSetting");

    ui_Loops = lv_obj_create(ui_PathSetting);
    lv_obj_remove_style_all(ui_Loops);
    lv_obj_set_width(ui_Loops, 460);
    lv_obj_set_height(ui_Loops, 114);
    lv_obj_set_x(ui_Loops, 0);
    lv_obj_set_y(ui_Loops, 252);
    lv_obj_set_align(ui_Loops, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Loops, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Loops, lv_color_hex(0xE3D9B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Loops, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoopValue = lv_obj_create(ui_Loops);
    lv_obj_set_width(ui_LoopValue, 81);
    lv_obj_set_height(ui_LoopValue, 59);
    lv_obj_set_x(ui_LoopValue, 80);
    lv_obj_set_y(ui_LoopValue, -7);
    lv_obj_set_align(ui_LoopValue, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LoopValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LoopValue, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LoopValue, lv_color_hex(0x6BB7B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoopValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedValue3 = lv_label_create(ui_LoopValue);
    lv_obj_set_width(ui_SpeedValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedValue3, 2);
    lv_obj_set_y(ui_SpeedValue3, 0);
    lv_obj_set_align(ui_SpeedValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValue3, "2");
    lv_obj_set_style_text_color(ui_SpeedValue3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpeedValue3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValue3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Plusloop = lv_button_create(ui_Loops);
    lv_obj_set_width(ui_Plusloop, 58);
    lv_obj_set_height(ui_Plusloop, 51);
    lv_obj_set_x(ui_Plusloop, -14);
    lv_obj_set_y(ui_Plusloop, -9);
    lv_obj_set_align(ui_Plusloop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Plusloop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Plusloop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Plusloop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Plusloop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Plusloop, &ui_img_1157729664, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Plusloop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Plusloop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Plusloop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minusloop = lv_button_create(ui_Loops);
    lv_obj_set_width(ui_Minusloop, 60);
    lv_obj_set_height(ui_Minusloop, 53);
    lv_obj_set_x(ui_Minusloop, 164);
    lv_obj_set_y(ui_Minusloop, -10);
    lv_obj_set_align(ui_Minusloop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Minusloop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Minusloop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Minusloop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Minusloop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Minusloop, &ui_img_1381505174, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Minusloop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Minusloop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Minusloop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Loops);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -144);
    lv_obj_set_y(ui_Label6, -6);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Number of \nLoops");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ABSpeed = lv_obj_create(ui_PathSetting);
    lv_obj_remove_style_all(ui_ABSpeed);
    lv_obj_set_width(ui_ABSpeed, 476);
    lv_obj_set_height(ui_ABSpeed, 472);
    lv_obj_set_x(ui_ABSpeed, 1);
    lv_obj_set_y(ui_ABSpeed, -64);
    lv_obj_set_align(ui_ABSpeed, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ABSpeed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ABSpeed, lv_color_hex(0xE3D9B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ABSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedSetAB = lv_slider_create(ui_ABSpeed);
    lv_slider_set_range(ui_speedSetAB, 10, 90);
    lv_slider_set_value(ui_speedSetAB, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_speedSetAB) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_speedSetAB, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_speedSetAB, 340);
    lv_obj_set_height(ui_speedSetAB, 50);
    lv_obj_set_x(ui_speedSetAB, 49);
    lv_obj_set_y(ui_speedSetAB, -108);
    lv_obj_set_align(ui_speedSetAB, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_speedSetAB, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speedSetAB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_speedSetAB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_speedSetAB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_speedSetAB, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_speedSetAB, lv_color_hex(0x72B6AE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speedSetAB, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_speedSetAB, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speedSetAB, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_speedSetAB, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_speedSetAB,
                                                                                                 lv_obj_get_style_pad_right(ui_speedSetAB, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Panel2 = lv_obj_create(ui_ABSpeed);
    lv_obj_set_width(ui_Panel2, 190);
    lv_obj_set_height(ui_Panel2, 59);
    lv_obj_set_x(ui_Panel2, 128);
    lv_obj_set_y(ui_Panel2, -22);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x6BB7B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedValueAB = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_SpeedValueAB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValueAB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedValueAB, 2);
    lv_obj_set_y(ui_SpeedValueAB, 0);
    lv_obj_set_align(ui_SpeedValueAB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValueAB, "50 mm/s");
    lv_obj_set_style_text_color(ui_SpeedValueAB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValueAB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpeedValueAB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValueAB, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlusAB = lv_button_create(ui_ABSpeed);
    lv_obj_set_width(ui_PlusAB, 58);
    lv_obj_set_height(ui_PlusAB, 51);
    lv_obj_set_x(ui_PlusAB, -155);
    lv_obj_set_y(ui_PlusAB, -17);
    lv_obj_set_align(ui_PlusAB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlusAB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PlusAB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PlusAB, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlusAB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_PlusAB, &ui_img_1157729664, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PlusAB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PlusAB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PlusAB, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinusAB = lv_button_create(ui_ABSpeed);
    lv_obj_set_width(ui_MinusAB, 60);
    lv_obj_set_height(ui_MinusAB, 53);
    lv_obj_set_x(ui_MinusAB, -47);
    lv_obj_set_y(ui_MinusAB, -18);
    lv_obj_set_align(ui_MinusAB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MinusAB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MinusAB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MinusAB, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinusAB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_MinusAB, &ui_img_1381505174, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MinusAB, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MinusAB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MinusAB, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_ABSpeed);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -182);
    lv_obj_set_y(ui_Label11, -112);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "A -> B \nSpeed");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_ABSpeed);
    lv_obj_set_width(ui_Panel4, 176);
    lv_obj_set_height(ui_Panel4, 59);
    lv_obj_set_x(ui_Panel4, 135);
    lv_obj_set_y(ui_Panel4, 175);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x6BB7B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedValueBA = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_SpeedValueBA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValueBA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedValueBA, 2);
    lv_obj_set_y(ui_SpeedValueBA, 0);
    lv_obj_set_align(ui_SpeedValueBA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValueBA, "50 mm/s");
    lv_obj_set_style_text_color(ui_SpeedValueBA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValueBA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpeedValueBA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValueBA, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlusBA = lv_button_create(ui_ABSpeed);
    lv_obj_set_width(ui_PlusBA, 58);
    lv_obj_set_height(ui_PlusBA, 51);
    lv_obj_set_x(ui_PlusBA, -158);
    lv_obj_set_y(ui_PlusBA, 181);
    lv_obj_set_align(ui_PlusBA, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PlusBA, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PlusBA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PlusBA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlusBA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_PlusBA, &ui_img_1157729664, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PlusBA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PlusBA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PlusBA, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinusBA = lv_button_create(ui_ABSpeed);
    lv_obj_set_width(ui_MinusBA, 60);
    lv_obj_set_height(ui_MinusBA, 53);
    lv_obj_set_x(ui_MinusBA, -44);
    lv_obj_set_y(ui_MinusBA, 178);
    lv_obj_set_align(ui_MinusBA, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MinusBA, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MinusBA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MinusBA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinusBA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_MinusBA, &ui_img_1381505174, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MinusBA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MinusBA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MinusBA, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_ABSpeed);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -176);
    lv_obj_set_y(ui_Label5, 90);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "B  -> A \nSpeed");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedSetBA = lv_slider_create(ui_ABSpeed);
    lv_slider_set_range(ui_speedSetBA, 10, 90);
    lv_slider_set_value(ui_speedSetBA, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_speedSetBA) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_speedSetBA, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_speedSetBA, 342);
    lv_obj_set_height(ui_speedSetBA, 50);
    lv_obj_set_x(ui_speedSetBA, 52);
    lv_obj_set_y(ui_speedSetBA, 94);
    lv_obj_set_align(ui_speedSetBA, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_speedSetBA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speedSetBA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_speedSetBA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_speedSetBA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_speedSetBA, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_speedSetBA, lv_color_hex(0x72B6AE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speedSetBA, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_speedSetBA, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speedSetBA, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_speedSetBA, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_speedSetBA,
                                                                                                 lv_obj_get_style_pad_right(ui_speedSetBA, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_SwitchCS = lv_switch_create(ui_PathSetting);
    lv_obj_set_width(ui_SwitchCS, 143);
    lv_obj_set_height(ui_SwitchCS, 59);
    lv_obj_set_x(ui_SwitchCS, -146);
    lv_obj_set_y(ui_SwitchCS, -259);
    lv_obj_set_align(ui_SwitchCS, LV_ALIGN_CENTER);

    lv_obj_set_style_border_color(ui_SwitchCS, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SwitchCS, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SwitchCS, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_PathSetting);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 79);
    lv_obj_set_y(ui_Label7, -266);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Same Speed");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button14, ui_event_Button14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_positionAB, ui_event_positionAB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_speedSetAB, ui_event_speedSetAB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlusAB, ui_event_PlusAB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MinusAB, ui_event_MinusAB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_speedSetBA, ui_event_speedSetBA, LV_EVENT_ALL, NULL);
    uic_Header2_battery = ui_comp_get_child(ui_Header2, UI_COMP_HEADER_BATTERY);
    uic_SliderPositionAB = ui_SliderPositionAB;
    uic_positionAB = ui_positionAB;
    uic_Start = ui_Start;
    uic_Stop = ui_Stop;
    uic_SetA = ui_SetA;
    uic_SetAValue = ui_SetAValue;
    uic_SetAValue1 = ui_SetAValue1;
    uic_SetBValue = ui_SetBValue;
    uic_SetBValue1 = ui_SetBValue1;
    uic_SetB = ui_SetB;
    uic_BackA = ui_BackA;
    uic_BackB = ui_BackB;
    uic_LoopValue = ui_LoopValue;
    uic_Plusloop = ui_Plusloop;
    uic_Minusloop = ui_Minusloop;
    uic_speedSetAB = ui_speedSetAB;
    uic_SpeedValueAB = ui_SpeedValueAB;
    uic_PlusAB = ui_PlusAB;
    uic_MinusAB = ui_MinusAB;
    uic_SpeedValueBA = ui_SpeedValueBA;
    uic_PlusBA = ui_PlusBA;
    uic_MinusBA = ui_MinusBA;
    uic_speedSetBA = ui_speedSetBA;
    uic_SwitchCS = ui_SwitchCS;

}

void ui_ABMode_screen_destroy(void)
{
    if(ui_ABMode) lv_obj_del(ui_ABMode);

    // NULL screen variables
    ui_ABMode = NULL;
    ui_Header2 = NULL;
    uic_Header2_battery = NULL;
    ui_Footer3 = NULL;
    ui_Panel11 = NULL;
    ui_Container14 = NULL;
    ui_Button14 = NULL;
    ui_Label23 = NULL;
    ui_Image27 = NULL;
    ui_power3 = NULL;
    ui_Image28 = NULL;
    ui_ABSetting = NULL;
    ui_ABPoint = NULL;
    ui_Slider6 = NULL;
    ui_Image13 = NULL;
    ui_Container9 = NULL;
    ui_Image15 = NULL;
    uic_SliderPositionAB = NULL;
    ui_SliderPositionAB = NULL;
    uic_positionAB = NULL;
    ui_positionAB = NULL;
    ui_Panel9 = NULL;
    uic_Start = NULL;
    ui_Start = NULL;
    ui_Starttext = NULL;
    uic_Stop = NULL;
    ui_Stop = NULL;
    ui_StopText = NULL;
    uic_SetA = NULL;
    ui_SetA = NULL;
    ui_SetAtext = NULL;
    uic_SetAValue = NULL;
    ui_SetAValue = NULL;
    uic_SetAValue1 = NULL;
    ui_SetAValue1 = NULL;
    uic_SetBValue = NULL;
    ui_SetBValue = NULL;
    uic_SetBValue1 = NULL;
    ui_SetBValue1 = NULL;
    uic_SetB = NULL;
    ui_SetB = NULL;
    ui_Btext = NULL;
    uic_BackA = NULL;
    ui_BackA = NULL;
    ui_BackAtext = NULL;
    uic_BackB = NULL;
    ui_BackB = NULL;
    ui_BackBtext = NULL;
    ui_PathSetting = NULL;
    ui_Loops = NULL;
    uic_LoopValue = NULL;
    ui_LoopValue = NULL;
    ui_SpeedValue3 = NULL;
    uic_Plusloop = NULL;
    ui_Plusloop = NULL;
    uic_Minusloop = NULL;
    ui_Minusloop = NULL;
    ui_Label6 = NULL;
    ui_ABSpeed = NULL;
    uic_speedSetAB = NULL;
    ui_speedSetAB = NULL;
    ui_Panel2 = NULL;
    uic_SpeedValueAB = NULL;
    ui_SpeedValueAB = NULL;
    uic_PlusAB = NULL;
    ui_PlusAB = NULL;
    uic_MinusAB = NULL;
    ui_MinusAB = NULL;
    ui_Label11 = NULL;
    ui_Panel4 = NULL;
    uic_SpeedValueBA = NULL;
    ui_SpeedValueBA = NULL;
    uic_PlusBA = NULL;
    ui_PlusBA = NULL;
    uic_MinusBA = NULL;
    ui_MinusBA = NULL;
    ui_Label5 = NULL;
    uic_speedSetBA = NULL;
    ui_speedSetBA = NULL;
    uic_SwitchCS = NULL;
    ui_SwitchCS = NULL;
    ui_Label7 = NULL;

}
