// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Slider_UI

#ifndef UI_BLANK_H
#define UI_BLANK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Blank
extern void ui_Blank_screen_init(void);
extern void ui_Blank_screen_destroy(void);
extern void ui_event_Blank(lv_event_t * e);
extern lv_obj_t * ui_Blank;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

