// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Slider_UI

#include "ui.h"

lv_obj_t * ui_Blank = NULL;
// event funtions
void ui_event_Blank(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Splash, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Splash_screen_init);
    }
}

// build funtions

void ui_Blank_screen_init(void)
{
    ui_Blank = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Blank, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Blank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Blank, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Blank, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Blank, ui_event_Blank, LV_EVENT_ALL, NULL);

}

void ui_Blank_screen_destroy(void)
{
    if(ui_Blank) lv_obj_del(ui_Blank);

    // NULL screen variables
    ui_Blank = NULL;

}
