// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Slider_UI

#include "ui.h"

lv_obj_t * uic_positionCM;
lv_obj_t * uic_SliderPositionCA;
lv_obj_t * uic_leftlimit;
lv_obj_t * uic_rightlimit;
lv_obj_t * uic_right;
lv_obj_t * uic_homebtn;
lv_obj_t * uic_left;
lv_obj_t * uic_calibrate;
lv_obj_t * uic_Header4_battery;
lv_obj_t * ui_Calibration = NULL;
lv_obj_t * ui_Header4 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_calibrate = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_left = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_homebtn = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Footer4 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Image29 = NULL;
lv_obj_t * ui_right = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Slider5 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_rightlimit = NULL;
lv_obj_t * ui_leftlimit = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_SliderPositionCA = NULL;
lv_obj_t * ui_positionCM = NULL;
// event funtions
void ui_event_Calibration(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_positionCM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SliderPositionCA, target, "", "");
    }
}

// build funtions

void ui_Calibration_screen_init(void)
{
    ui_Calibration = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Calibration, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header4 = ui_Header_create(ui_Calibration);
    lv_obj_set_x(ui_Header4, -1);
    lv_obj_set_y(ui_Header4, -361);

    lv_label_set_text(ui_comp_get_child(ui_Header4, UI_COMP_HEADER_LABEL1), "Calibration");

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_Button1 = lv_button_create(ui_Calibration);
    lv_obj_set_width(ui_Button1, 150);
    lv_obj_set_height(ui_Button1, 150);
    lv_obj_set_x(ui_Button1, -1897);
    lv_obj_set_y(ui_Button1, -110);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_calibrate = lv_button_create(ui_Calibration);
    lv_obj_set_width(ui_calibrate, 150);
    lv_obj_set_height(ui_calibrate, 100);
    lv_obj_set_x(ui_calibrate, 129);
    lv_obj_set_y(ui_calibrate, 24);
    lv_obj_set_align(ui_calibrate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_calibrate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_calibrate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_calibrate, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_calibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_calibrate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_calibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_calibrate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_calibrate, lv_color_hex(0xC0980F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_calibrate, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_calibrate, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_calibrate);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Calibrate");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label13, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_left = lv_button_create(ui_Calibration);
    lv_obj_set_width(ui_left, 150);
    lv_obj_set_height(ui_left, 100);
    lv_obj_set_x(ui_left, -139);
    lv_obj_set_y(ui_left, 210);
    lv_obj_set_align(ui_left, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_left, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_left, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_left, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_left, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_left, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_left);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Left");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label14, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label14, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebtn = lv_button_create(ui_Calibration);
    lv_obj_set_width(ui_homebtn, 150);
    lv_obj_set_height(ui_homebtn, 100);
    lv_obj_set_x(ui_homebtn, -138);
    lv_obj_set_y(ui_homebtn, 30);
    lv_obj_set_align(ui_homebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homebtn, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_homebtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_homebtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_homebtn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_homebtn);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Home");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label16, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Footer4 = lv_obj_create(ui_Calibration);
    lv_obj_remove_style_all(ui_Footer4);
    lv_obj_set_width(ui_Footer4, 500);
    lv_obj_set_height(ui_Footer4, 54);
    lv_obj_set_x(ui_Footer4, 2);
    lv_obj_set_y(ui_Footer4, 378);
    lv_obj_set_align(ui_Footer4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Footer4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel12 = lv_obj_create(ui_Footer4);
    lv_obj_set_width(ui_Panel12, 500);
    lv_obj_set_height(ui_Panel12, 50);
    lv_obj_set_x(ui_Panel12, -3);
    lv_obj_set_y(ui_Panel12, 0);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x8693A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel12, lv_color_hex(0x31363B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel12, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Footer4);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 63);
    lv_obj_set_height(ui_Container15, 27);
    lv_obj_set_x(ui_Container15, -194);
    lv_obj_set_y(ui_Container15, 0);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container15, 202, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_button_create(ui_Footer4);
    lv_obj_set_width(ui_Button15, 92);
    lv_obj_set_height(ui_Button15, 35);
    lv_obj_set_x(ui_Button15, -184);
    lv_obj_set_y(ui_Button15, -1);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button15, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Button15);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -15);
    lv_obj_set_y(ui_Label24, 0);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "Back");

    ui_Image29 = lv_image_create(ui_Button15);
    lv_image_set_src(ui_Image29, &ui_img_16417679);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image29, 26);
    lv_obj_set_y(ui_Image29, 0);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_right = lv_button_create(ui_Calibration);
    lv_obj_set_width(ui_right, 150);
    lv_obj_set_height(ui_right, 100);
    lv_obj_set_x(ui_right, 131);
    lv_obj_set_y(ui_right, 213);
    lv_obj_set_align(ui_right, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_right, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_right, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_right, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_right, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_right, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_right);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Right");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label15, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider5 = lv_obj_create(ui_Calibration);
    lv_obj_remove_style_all(ui_Slider5);
    lv_obj_set_width(ui_Slider5, 462);
    lv_obj_set_height(ui_Slider5, 157);
    lv_obj_set_x(ui_Slider5, 0);
    lv_obj_set_y(ui_Slider5, -140);
    lv_obj_set_align(ui_Slider5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Slider5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_image_create(ui_Slider5);
    lv_image_set_src(ui_Image12, &ui_img_rectangle_114_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 389
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image12, -5);
    lv_obj_set_y(ui_Image12, -37);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightlimit = lv_obj_create(ui_Slider5);
    lv_obj_set_width(ui_rightlimit, 24);
    lv_obj_set_height(ui_rightlimit, 22);
    lv_obj_set_x(ui_rightlimit, 175);
    lv_obj_set_y(ui_rightlimit, 6);
    lv_obj_set_align(ui_rightlimit, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rightlimit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_rightlimit, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rightlimit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightlimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftlimit = lv_obj_create(ui_Slider5);
    lv_obj_set_width(ui_leftlimit, 24);
    lv_obj_set_height(ui_leftlimit, 22);
    lv_obj_set_x(ui_leftlimit, -187);
    lv_obj_set_y(ui_leftlimit, 7);
    lv_obj_set_align(ui_leftlimit, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_leftlimit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_leftlimit, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_leftlimit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftlimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Slider5);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 452);
    lv_obj_set_height(ui_Container7, 143);
    lv_obj_set_x(ui_Container7, -1);
    lv_obj_set_y(ui_Container7, 4);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_image_create(ui_Container7);
    lv_image_set_src(ui_Image8, &ui_img_infomer_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Image8, 2);
    lv_obj_set_y(ui_Image8, 18);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderPositionCA = lv_label_create(ui_Image8);
    lv_obj_set_width(ui_SliderPositionCA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SliderPositionCA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SliderPositionCA, 0);
    lv_obj_set_y(ui_SliderPositionCA, 9);
    lv_obj_set_align(ui_SliderPositionCA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SliderPositionCA, "0");
    lv_obj_set_style_text_color(ui_SliderPositionCA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SliderPositionCA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderPositionCA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPositionCA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_positionCM = lv_slider_create(ui_Container7);
    lv_slider_set_value(ui_positionCM, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_positionCM) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_positionCM, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_positionCM, 378);
    lv_obj_set_height(ui_positionCM, 44);
    lv_obj_set_x(ui_positionCM, -4);
    lv_obj_set_y(ui_positionCM, -41);
    lv_obj_set_align(ui_positionCM, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_positionCM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionCM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_positionCM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_positionCM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_positionCM, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_positionCM, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionCM, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_positionCM, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionCM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_positionCM, &ui_img_box_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_positionCM, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_positionCM,
                                                                                                 lv_obj_get_style_pad_right(ui_positionCM, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_positionCM, ui_event_positionCM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Calibration, ui_event_Calibration, LV_EVENT_ALL, NULL);
    uic_Header4_battery = ui_comp_get_child(ui_Header4, UI_COMP_HEADER_BATTERY);
    uic_calibrate = ui_calibrate;
    uic_left = ui_left;
    uic_homebtn = ui_homebtn;
    uic_right = ui_right;
    uic_rightlimit = ui_rightlimit;
    uic_leftlimit = ui_leftlimit;
    uic_SliderPositionCA = ui_SliderPositionCA;
    uic_positionCM = ui_positionCM;

}

void ui_Calibration_screen_destroy(void)
{
    if(ui_Calibration) lv_obj_del(ui_Calibration);

    // NULL screen variables
    ui_Calibration = NULL;
    ui_Header4 = NULL;
    uic_Header4_battery = NULL;
    ui_Button1 = NULL;
    uic_calibrate = NULL;
    ui_calibrate = NULL;
    ui_Label13 = NULL;
    uic_left = NULL;
    ui_left = NULL;
    ui_Label14 = NULL;
    uic_homebtn = NULL;
    ui_homebtn = NULL;
    ui_Label16 = NULL;
    ui_Footer4 = NULL;
    ui_Panel12 = NULL;
    ui_Container15 = NULL;
    ui_Button15 = NULL;
    ui_Label24 = NULL;
    ui_Image29 = NULL;
    uic_right = NULL;
    ui_right = NULL;
    ui_Label15 = NULL;
    ui_Slider5 = NULL;
    ui_Image12 = NULL;
    uic_rightlimit = NULL;
    ui_rightlimit = NULL;
    uic_leftlimit = NULL;
    ui_leftlimit = NULL;
    ui_Container7 = NULL;
    ui_Image8 = NULL;
    uic_SliderPositionCA = NULL;
    ui_SliderPositionCA = NULL;
    uic_positionCM = NULL;
    ui_positionCM = NULL;

}
