// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Slider_UI

#ifndef UI_CALIBRATION_H
#define UI_CALIBRATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Calibration
extern void ui_Calibration_screen_init(void);
extern void ui_Calibration_screen_destroy(void);
extern void ui_event_Calibration(lv_event_t * e);
extern lv_obj_t * ui_Calibration;
extern lv_obj_t * ui_Header4;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_calibrate;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_left;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_homebtn;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Footer4;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Container15;
extern void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Image29;
extern lv_obj_t * ui_right;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Slider5;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_SliderPositionCA;
extern void ui_event_positionCM(lv_event_t * e);
extern lv_obj_t * ui_positionCM;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Header4_battery;
extern lv_obj_t * uic_calibrate;
extern lv_obj_t * uic_left;
extern lv_obj_t * uic_homebtn;
extern lv_obj_t * uic_right;
extern lv_obj_t * uic_SliderPositionCA;
extern lv_obj_t * uic_positionCM;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

