// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Slider_UI

#ifndef UI_MANUALMODE_H
#define UI_MANUALMODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ManualMode
extern void ui_ManualMode_screen_init(void);
extern void ui_ManualMode_screen_destroy(void);
extern lv_obj_t * ui_ManualMode;
extern lv_obj_t * ui_Header1;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_Jog_Mode;
extern lv_obj_t * ui_Move;
extern lv_obj_t * ui_leftMove;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_SpeedValue;
extern lv_obj_t * ui_rightMove;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Container3;
extern void ui_event_speedSet(lv_event_t * e);
extern lv_obj_t * ui_speedSet;
extern void ui_event_Plus(lv_event_t * e);
extern lv_obj_t * ui_Plus;
extern void ui_event_Minus(lv_event_t * e);
extern lv_obj_t * ui_Minus;
extern lv_obj_t * ui_Slider;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_SliderPositionJM;
extern void ui_event_positionJM(lv_event_t * e);
extern lv_obj_t * ui_positionJM;
extern lv_obj_t * ui_Position_Mode;
extern void ui_event_positionSlider(lv_event_t * e);
extern lv_obj_t * ui_positionSlider;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_PositionValue;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_positionPM;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_SliderPositionPM;
extern void ui_event_PositionMPM(lv_event_t * e);
extern lv_obj_t * ui_PositionMPM;
extern lv_obj_t * ui_Footer2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Container5;
extern void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image11;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Header1_battery;
extern lv_obj_t * uic_TabView2;
extern lv_obj_t * uic_leftMove;
extern lv_obj_t * uic_rightMove;
extern lv_obj_t * uic_speedSet;
extern lv_obj_t * uic_SliderPositionJM;
extern lv_obj_t * uic_positionJM;
extern lv_obj_t * uic_positionSlider;
extern lv_obj_t * uic_SliderPositionPM;
extern lv_obj_t * uic_PositionMPM;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

