// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Slider_UI

#include "ui.h"

lv_obj_t * uic_PositionMPM;
lv_obj_t * uic_SliderPositionPM;
lv_obj_t * uic_positionSlider;
lv_obj_t * uic_positionJM;
lv_obj_t * uic_SliderPositionJM;
lv_obj_t * uic_speedSet;
lv_obj_t * uic_rightMove;
lv_obj_t * uic_leftMove;
lv_obj_t * uic_TabView2;
lv_obj_t * uic_Header1_battery;
lv_obj_t * ui_ManualMode = NULL;
lv_obj_t * ui_Header1 = NULL;
lv_obj_t * ui_TabView2 = NULL;
lv_obj_t * ui_Jog_Mode = NULL;
lv_obj_t * ui_Move = NULL;
lv_obj_t * ui_leftMove = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_SpeedValue = NULL;
lv_obj_t * ui_rightMove = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_speedSet = NULL;
lv_obj_t * ui_Plus = NULL;
lv_obj_t * ui_Minus = NULL;
lv_obj_t * ui_Slider = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_SliderPositionJM = NULL;
lv_obj_t * ui_positionJM = NULL;
lv_obj_t * ui_Position_Mode = NULL;
lv_obj_t * ui_positionSlider = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_PositionValue = NULL;
lv_obj_t * ui_Button13 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_positionPM = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_SliderPositionPM = NULL;
lv_obj_t * ui_PositionMPM = NULL;
lv_obj_t * ui_Footer2 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Image11 = NULL;
// event funtions
void ui_event_speedSet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SpeedValue, target, "", "\nmm/s");
    }
}

void ui_event_Plus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_slider_increment(ui_speedSet, 1, LV_ANIM_ON);
    }
}

void ui_event_Minus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_slider_increment(ui_speedSet, -1, LV_ANIM_ON);
    }
}

void ui_event_positionJM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SliderPositionJM, target, "", "");
    }
}

void ui_event_positionSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_PositionValue, target, "", " mm");
    }
}

void ui_event_PositionMPM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SliderPositionJM, target, "", "");
    }
}

void ui_event_Button12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

// build funtions

void ui_ManualMode_screen_init(void)
{
    ui_ManualMode = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ManualMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_recolor(ui_ManualMode, lv_color_hex(0x929292), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_ManualMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_image_recolor(ui_ManualMode, lv_color_hex(0x717171), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_ManualMode, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ManualMode, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ManualMode, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Header1 = ui_Header_create(ui_ManualMode);
    lv_obj_set_x(ui_Header1, 0);
    lv_obj_set_y(ui_Header1, -360);

    lv_label_set_text(ui_comp_get_child(ui_Header1, UI_COMP_HEADER_LABEL1), "Manual");

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    ui_TabView2 = lv_tabview_create(ui_ManualMode);
    lv_tabview_set_tab_bar_size(ui_TabView2, 100);
    lv_obj_set_width(ui_TabView2, 480);
    lv_obj_set_height(ui_TabView2, 685);
    lv_obj_set_x(ui_TabView2, 0);
    lv_obj_set_y(ui_TabView2, 18);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_text_color(lv_tabview_get_tab_bar(ui_TabView2), lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_bar(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_TabView2), &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_tabview_get_tab_bar(ui_TabView2), 5,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(lv_tabview_get_tab_bar(ui_TabView2), lv_color_hex(0xB5B5B5),
                                      LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(lv_tabview_get_tab_bar(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_bar(ui_TabView2), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_bar(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_bar(ui_TabView2), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Jog_Mode = lv_tabview_add_tab(ui_TabView2, "Jog Mode");

    ui_Move = lv_obj_create(ui_Jog_Mode);
    lv_obj_remove_style_all(ui_Move);
    lv_obj_set_width(ui_Move, 470);
    lv_obj_set_height(ui_Move, 150);
    lv_obj_set_x(ui_Move, 1);
    lv_obj_set_y(ui_Move, 176);
    lv_obj_set_align(ui_Move, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Move, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leftMove = lv_button_create(ui_Move);
    lv_obj_set_width(ui_leftMove, 150);
    lv_obj_set_height(ui_leftMove, 150);
    lv_obj_set_x(ui_leftMove, -149);
    lv_obj_set_y(ui_leftMove, 1);
    lv_obj_set_align(ui_leftMove, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftMove, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_leftMove, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_leftMove, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_leftMove, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_leftMove);
    lv_image_set_src(ui_Image4, &ui_img_back_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Move);
    lv_obj_set_width(ui_Panel1, 120);
    lv_obj_set_height(ui_Panel1, 150);
    lv_obj_set_x(ui_Panel1, -2);
    lv_obj_set_y(ui_Panel1, 1);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x31363B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedValue = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_SpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedValue, -1);
    lv_obj_set_y(ui_SpeedValue, -7);
    lv_obj_set_align(ui_SpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValue, "50 \nmm/s");
    lv_obj_set_style_text_color(ui_SpeedValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpeedValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValue, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rightMove = lv_button_create(ui_Move);
    lv_obj_set_width(ui_rightMove, 150);
    lv_obj_set_height(ui_rightMove, 150);
    lv_obj_set_x(ui_rightMove, 151);
    lv_obj_set_y(ui_rightMove, 0);
    lv_obj_set_align(ui_rightMove, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightMove, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_rightMove, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rightMove, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rightMove, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_rightMove);
    lv_image_set_src(ui_Image5, &ui_img_back2_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 80
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Jog_Mode);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 458);
    lv_obj_set_height(ui_Container3, 116);
    lv_obj_set_x(ui_Container3, -9);
    lv_obj_set_y(ui_Container3, 20);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_speedSet = lv_slider_create(ui_Container3);
    lv_slider_set_range(ui_speedSet, 10, 90);
    lv_slider_set_value(ui_speedSet, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_speedSet) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_speedSet, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_speedSet, 290);
    lv_obj_set_height(ui_speedSet, 50);
    lv_obj_set_x(ui_speedSet, -80);
    lv_obj_set_y(ui_speedSet, 3);
    lv_obj_set_align(ui_speedSet, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_speedSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speedSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_speedSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_speedSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_speedSet, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_speedSet, lv_color_hex(0x72B6AE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speedSet, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_speedSet, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speedSet, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_speedSet, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_speedSet,
                                                                                               lv_obj_get_style_pad_right(ui_speedSet, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Plus = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_Plus, 58);
    lv_obj_set_height(ui_Plus, 51);
    lv_obj_set_x(ui_Plus, 116);
    lv_obj_set_y(ui_Plus, 2);
    lv_obj_set_align(ui_Plus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Plus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Plus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Plus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Plus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Plus, &ui_img_1157729664, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Plus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Plus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Plus, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minus = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_Minus, 60);
    lv_obj_set_height(ui_Minus, 53);
    lv_obj_set_x(ui_Minus, 195);
    lv_obj_set_y(ui_Minus, 2);
    lv_obj_set_align(ui_Minus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Minus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Minus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Minus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Minus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Minus, &ui_img_1381505174, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Minus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Minus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Minus, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider = lv_obj_create(ui_Jog_Mode);
    lv_obj_remove_style_all(ui_Slider);
    lv_obj_set_width(ui_Slider, 462);
    lv_obj_set_height(ui_Slider, 157);
    lv_obj_set_x(ui_Slider, -2);
    lv_obj_set_y(ui_Slider, -132);
    lv_obj_set_align(ui_Slider, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Slider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_image_create(ui_Slider);
    lv_image_set_src(ui_Image6, &ui_img_rectangle_114_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 389
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image6, -5);
    lv_obj_set_y(ui_Image6, -37);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container10 = lv_obj_create(ui_Slider);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 452);
    lv_obj_set_height(ui_Container10, 143);
    lv_obj_set_x(ui_Container10, -1);
    lv_obj_set_y(ui_Container10, 4);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_image_create(ui_Container10);
    lv_image_set_src(ui_Image7, &ui_img_infomer_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Image7, 2);
    lv_obj_set_y(ui_Image7, 18);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderPositionJM = lv_label_create(ui_Image7);
    lv_obj_set_width(ui_SliderPositionJM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SliderPositionJM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SliderPositionJM, 0);
    lv_obj_set_y(ui_SliderPositionJM, 9);
    lv_obj_set_align(ui_SliderPositionJM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SliderPositionJM, "0");
    lv_obj_set_style_text_color(ui_SliderPositionJM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SliderPositionJM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderPositionJM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPositionJM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_positionJM = lv_slider_create(ui_Container10);
    lv_slider_set_value(ui_positionJM, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_positionJM) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_positionJM, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_positionJM, 378);
    lv_obj_set_height(ui_positionJM, 44);
    lv_obj_set_x(ui_positionJM, -4);
    lv_obj_set_y(ui_positionJM, -41);
    lv_obj_set_align(ui_positionJM, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_positionJM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionJM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_positionJM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_positionJM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_positionJM, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_positionJM, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionJM, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_positionJM, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionJM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_positionJM, &ui_img_box_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_positionJM, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_positionJM,
                                                                                                 lv_obj_get_style_pad_right(ui_positionJM, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Position_Mode = lv_tabview_add_tab(ui_TabView2, "Position Mode");

    ui_positionSlider = lv_slider_create(ui_Position_Mode);
    lv_slider_set_range(ui_positionSlider, 0, 1000);
    lv_slider_set_value(ui_positionSlider, 500, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_positionSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_positionSlider, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_positionSlider, 415);
    lv_obj_set_height(ui_positionSlider, 50);
    lv_obj_set_x(ui_positionSlider, 1);
    lv_obj_set_y(ui_positionSlider, 38);
    lv_obj_set_align(ui_positionSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_positionSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_positionSlider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_positionSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_positionSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_positionSlider, lv_color_hex(0x72B6AE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_positionSlider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_positionSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_positionSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_positionSlider,
                                                                                                     lv_obj_get_style_pad_right(ui_positionSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Panel7 = lv_obj_create(ui_Position_Mode);
    lv_obj_set_width(ui_Panel7, 429);
    lv_obj_set_height(ui_Panel7, 71);
    lv_obj_set_x(ui_Panel7, 1);
    lv_obj_set_y(ui_Panel7, 203);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x72B6AD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PositionValue = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_PositionValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PositionValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PositionValue, -111);
    lv_obj_set_y(ui_PositionValue, 1);
    lv_obj_set_align(ui_PositionValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PositionValue, "500  mm");
    lv_obj_set_style_text_color(ui_PositionValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PositionValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PositionValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PositionValue, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button13 = lv_button_create(ui_Panel7);
    lv_obj_set_width(ui_Button13, 100);
    lv_obj_set_height(ui_Button13, 50);
    lv_obj_set_x(ui_Button13, 125);
    lv_obj_set_y(ui_Button13, 1);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0x72B6AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button13, lv_color_hex(0xCDB33F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button13, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button13, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button13);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Set");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label8, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_positionPM = lv_obj_create(ui_Position_Mode);
    lv_obj_remove_style_all(ui_positionPM);
    lv_obj_set_width(ui_positionPM, 462);
    lv_obj_set_height(ui_positionPM, 157);
    lv_obj_set_x(ui_positionPM, 3);
    lv_obj_set_y(ui_positionPM, -153);
    lv_obj_set_align(ui_positionPM, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_positionPM, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_image_create(ui_positionPM);
    lv_image_set_src(ui_Image20, &ui_img_rectangle_114_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 389
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image20, -5);
    lv_obj_set_y(ui_Image20, -37);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_positionPM);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 452);
    lv_obj_set_height(ui_Container4, 143);
    lv_obj_set_x(ui_Container4, -1);
    lv_obj_set_y(ui_Container4, 4);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_image_create(ui_Container4);
    lv_image_set_src(ui_Image18, &ui_img_infomer_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 57
    lv_obj_set_x(ui_Image18, 2);
    lv_obj_set_y(ui_Image18, 18);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderPositionPM = lv_label_create(ui_Image18);
    lv_obj_set_width(ui_SliderPositionPM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SliderPositionPM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SliderPositionPM, 0);
    lv_obj_set_y(ui_SliderPositionPM, 9);
    lv_obj_set_align(ui_SliderPositionPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SliderPositionPM, "0");
    lv_obj_set_style_text_color(ui_SliderPositionPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SliderPositionPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderPositionPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderPositionPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PositionMPM = lv_slider_create(ui_Container4);
    lv_slider_set_value(ui_PositionMPM, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_PositionMPM) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_PositionMPM, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_PositionMPM, 378);
    lv_obj_set_height(ui_PositionMPM, 44);
    lv_obj_set_x(ui_PositionMPM, -4);
    lv_obj_set_y(ui_PositionMPM, -41);
    lv_obj_set_align(ui_PositionMPM, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_PositionMPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PositionMPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PositionMPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PositionMPM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_PositionMPM, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PositionMPM, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PositionMPM, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PositionMPM, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PositionMPM, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_PositionMPM, &ui_img_box_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_PositionMPM, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_PositionMPM,
                                                                                                  lv_obj_get_style_pad_right(ui_PositionMPM, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Footer2 = lv_obj_create(ui_ManualMode);
    lv_obj_remove_style_all(ui_Footer2);
    lv_obj_set_width(ui_Footer2, 500);
    lv_obj_set_height(ui_Footer2, 54);
    lv_obj_set_x(ui_Footer2, 2);
    lv_obj_set_y(ui_Footer2, 378);
    lv_obj_set_align(ui_Footer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Footer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Footer2);
    lv_obj_set_width(ui_Panel5, 500);
    lv_obj_set_height(ui_Panel5, 50);
    lv_obj_set_x(ui_Panel5, -3);
    lv_obj_set_y(ui_Panel5, 0);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x8693A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel5, lv_color_hex(0x31363B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel5, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Footer2);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 63);
    lv_obj_set_height(ui_Container5, 27);
    lv_obj_set_x(ui_Container5, -194);
    lv_obj_set_y(ui_Container5, 0);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container5, 202, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_button_create(ui_Footer2);
    lv_obj_set_width(ui_Button12, 92);
    lv_obj_set_height(ui_Button12, 35);
    lv_obj_set_x(ui_Button12, -184);
    lv_obj_set_y(ui_Button12, -1);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button12, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button12, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -15);
    lv_obj_set_y(ui_Label10, 0);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Back");

    ui_Image11 = lv_image_create(ui_Button12);
    lv_image_set_src(ui_Image11, &ui_img_16417679);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image11, 26);
    lv_obj_set_y(ui_Image11, 0);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_speedSet, ui_event_speedSet, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Plus, ui_event_Plus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Minus, ui_event_Minus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_positionJM, ui_event_positionJM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_positionSlider, ui_event_positionSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PositionMPM, ui_event_PositionMPM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button12, ui_event_Button12, LV_EVENT_ALL, NULL);
    uic_Header1_battery = ui_comp_get_child(ui_Header1, UI_COMP_HEADER_BATTERY);
    uic_TabView2 = ui_TabView2;
    uic_leftMove = ui_leftMove;
    uic_rightMove = ui_rightMove;
    uic_speedSet = ui_speedSet;
    uic_SliderPositionJM = ui_SliderPositionJM;
    uic_positionJM = ui_positionJM;
    uic_positionSlider = ui_positionSlider;
    uic_SliderPositionPM = ui_SliderPositionPM;
    uic_PositionMPM = ui_PositionMPM;

}

void ui_ManualMode_screen_destroy(void)
{
    if(ui_ManualMode) lv_obj_del(ui_ManualMode);

    // NULL screen variables
    ui_ManualMode = NULL;
    ui_Header1 = NULL;
    uic_Header1_battery = NULL;
    uic_TabView2 = NULL;
    ui_TabView2 = NULL;
    ui_Jog_Mode = NULL;
    ui_Move = NULL;
    uic_leftMove = NULL;
    ui_leftMove = NULL;
    ui_Image4 = NULL;
    ui_Panel1 = NULL;
    ui_SpeedValue = NULL;
    uic_rightMove = NULL;
    ui_rightMove = NULL;
    ui_Image5 = NULL;
    ui_Container3 = NULL;
    uic_speedSet = NULL;
    ui_speedSet = NULL;
    ui_Plus = NULL;
    ui_Minus = NULL;
    ui_Slider = NULL;
    ui_Image6 = NULL;
    ui_Container10 = NULL;
    ui_Image7 = NULL;
    uic_SliderPositionJM = NULL;
    ui_SliderPositionJM = NULL;
    uic_positionJM = NULL;
    ui_positionJM = NULL;
    ui_Position_Mode = NULL;
    uic_positionSlider = NULL;
    ui_positionSlider = NULL;
    ui_Panel7 = NULL;
    ui_PositionValue = NULL;
    ui_Button13 = NULL;
    ui_Label8 = NULL;
    ui_positionPM = NULL;
    ui_Image20 = NULL;
    ui_Container4 = NULL;
    ui_Image18 = NULL;
    uic_SliderPositionPM = NULL;
    ui_SliderPositionPM = NULL;
    uic_PositionMPM = NULL;
    ui_PositionMPM = NULL;
    ui_Footer2 = NULL;
    ui_Panel5 = NULL;
    ui_Container5 = NULL;
    ui_Button12 = NULL;
    ui_Label10 = NULL;
    ui_Image11 = NULL;

}
