// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Slider_UI

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Header;
extern lv_obj_t * ui_Container2;
extern void ui_event_Manual(lv_event_t * e);
extern lv_obj_t * ui_Manual;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container6;
extern void ui_event_Manual3(lv_event_t * e);
extern lv_obj_t * ui_Manual3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container8;
extern void ui_event_Manual4(lv_event_t * e);
extern lv_obj_t * ui_Manual4;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Header_battery;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

